apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: customer-profile-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: experimental
  owner: default-team
  system: test
  definition: |
    components:
        schemas:
            CustomerProfileCreateRequest:
                properties:
                    email:
                        type: string
                    firstName:
                        type: string
                    lastName:
                        type: string
                required:
                    - email
                type: object
            CustomerProfileResponse:
                properties:
                    email:
                        type: string
                    firstName:
                        type: string
                    id:
                        type: string
                    lastName:
                        type: string
                required:
                    - email
                    - id
                type: object
    info:
        title: Customer Profile Management API
        version: "1.0"
    openapi: 3.0.1
    paths:
        /api/customer-profiles:
            post:
                operationId: create
                requestBody:
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CustomerProfileCreateRequest'
                    required: true
                responses:
                    "201":
                        content:
                            '*/*':
                                schema:
                                    $ref: '#/components/schemas/CustomerProfileResponse'
                        description: Customer profile successfully saved.
                        headers:
                            Location:
                                description: Contains path which can be used to retrieve saved profile. Last element is it's ID.
                                required: true
                                schema:
                                    type: string
                                style: simple
                    "400":
                        content:
                            '*/*':
                                schema:
                                    $ref: '#/components/schemas/CustomerProfileResponse'
                        description: Passed customer profile is invalid.
                summary: Saves provided customer profile.
                tags:
                    - Customer Profile CRUD
        /api/customer-profiles/{id}:
            get:
                operationId: get
                parameters:
                    - in: path
                    name: id
                    required: true
                    schema:
                        type: string
                responses:
                    "200":
                        content:
                            '*/*':
                                schema:
                                    $ref: '#/components/schemas/CustomerProfileResponse'
                        description: Customer profile retrieved successfully.
                    "404":
                        content:
                            '*/*':
                                schema:
                                    $ref: '#/components/schemas/CustomerProfileResponse'
                        description: Customer profile not found.
                summary: Get customer profile.
                tags:
                    - Customer Profile CRUD
    servers:
        - url: http://customer-profile.default.apps.34.139.6.200.nip.io
    tags:
        - name: Customer Profile REST API
